### ISSUE TITLE
OBD SCANNER NOT DETECTING ECU

### ISSUE THREAD

**Issue by rakshitbharat** [sugiuraii/ECUSim#2]
Hello,
I used your project but my OBD2 is not sending/receiving data.
OBD2 SCANNER BLUETOOTH (connected with mobile successfully)

Now what to do ?
It way ECU NOT CONNECTED

**Comment by sugiuraii** [comment]
Thank you for your comment. 

Which app do you have a trouble?

On some apps, auto ECU protocol detection (ATSP0 in ELM327 command) may fail.
In this case, the issue might be solved by setting ECU protocol manually.
(ECU protocol of this code is "ISO 15765-4 CAN (250kbps 11bit)". i.e. ATSP8).

Actually, I have to set the protocol manually on using this app.
https://play.google.com/store/apps/details?id=com.ovz.carscanner

I hope this will help.

**Comment by rakshitbharat** [comment]
I have tried all apps from play Store almost,
I also ordered 2 new OBD SCANNER let's wait for its arrival.
Will give updates here, may be my Bluetooth can be a problem.
BTW I appreciate this project.

Thanks

**Comment by rakshitbharat** [comment]
![Screenshot_20230509-214616_Car Scanner](https://github.com/sugiuraii/ECUSim/assets/17176729/87a445f4-b220-45b6-9777-7313de55b7fb)

Check this image

**Comment by rakshitbharat** [comment]
![Screenshot_20230509-215050_Car Scanner](https://github.com/sugiuraii/ECUSim/assets/17176729/a5c56907-cd1d-4b05-a400-314dc4b94d45)

**Comment by rakshitbharat** [comment]
16:25:03.990 -> Msg from canId: 7DF
16:25:04.030 -> PID query: 0
16:25:04.030 -> CAN message handle time (micros): 3664
16:25:04.030 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
16:25:04.030 -> - SRAM left: 1412
16:25:05.466 -> CAN message handle start.
16:25:05.466 -> Msg from canId: 98DB33F1
16:25:05.466 -> CAM ID do not match with this ECU's ID.
16:25:11.784 -> CAN message handle start.
16:25:11.784 -> Msg from canId: 98DB33F1
16:25:11.784 -> CAM ID do not match with this ECU's ID.
16:25:18.115 -> CAN message handle start.
16:25:18.115 -> Msg from canId: 98DB33F1
16:25:18.115 -> CAM ID do not match with this ECU's ID.
16:25:24.417 -> CAN message handle start.
16:25:24.417 -> Msg from canId: 98DB33F1
16:25:24.460 -> CAM ID do not match with this ECU's ID.
16:25:30.759 -> CAN message handle start.
16:25:30.759 -> Msg from canId: 7DF
16:25:30.759 -> PID query: 0
16:25:30.759 -> CAN message handle time (micros): 3672
16:25:30.759 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
16:25:30.759 -> - SRAM left: 1412
16:25:30.790 -> CAN message handle start.
16:25:30.790 -> Msg from canId: 98DB33F1
16:25:30.823 -> CAM ID do not match with this ECU's ID.
16:25:37.086 -> CAN message handle start.
16:25:37.086 -> Msg from canId: 7DF
16:25:37.086 -> PID query: 0
16:25:37.086 -> CAN message handle time (micros): 3664
16:25:37.086 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
16:25:37.086 -> - SRAM left: 1412
16:25:37.163 -> CAN message handle start.
16:25:37.163 -> Msg from canId: 98DB33F1
16:25:37.163 -> CAM ID do not match with this ECU's ID

**Comment by sugiuraii** [comment]
Thank you for your report.
I will check the operation by myself, after returning home.

On your log,
>

**Comment by rakshitbharat** [comment]
Please include me in the project,
I would like to be the part of the project.
Will try to help in testing and development
I am full stack developer.


Thanks

**Comment by sugiuraii** [comment]
I‘m sorry I closed the issue by mistake.
Thank you for your report. I will check by myself after returning home.

On your log, I noticed several point...

- ECUSim seems to respond PID request of 00 by CAN ID 7DF (broadcast). However, the app invokes no ECU connection error.    

 l’m wondering why this happens.

- The other strange point is that the message of 29bit CAN ID (98DB33F1, actual ID is 18DB33F1, same meaning as 7DF). exist on your log, even though 11bit CAN ID is set on the app.

Anyway, I will check deeply after returning home.

**Comment by rakshitbharat** [comment]
Sure, let me know incase you need any realtime help.

Thanks

**Comment by sugiuraii** [comment]
I checked the operation by using my no brand bluetooth ELM327 adapter.
I could't reproduce your problem.

The connection works well only by changing ECU protocol to CAN 250kbps, 11bit ID.
(Please see attached video clip).

https://github.com/sugiuraii/ECUSim/assets/25734871/5fe7135d-b3c9-43cd-bf2f-a4f8863d7dd5

**Comment by rakshitbharat** [comment]
Thanks for the update,
Tomorrow my new OBD2 Is coming let me try with it.
I will inform about that here.

Thanks

**Comment by sugiuraii** [comment]
Here is a logfile from ECUSim debug mode.

The remarkable point is that there is no communication of CAN 29bit ID.

I have no idea why your communication log has the communication of CAN 29bit ID. 
But this might be the key to solve your issue.

[ECUSimLog_CarScanner_NoBrandBluetoothELM327_20230510.txt](https://github.com/sugiuraii/ECUSim/files/11443511/ECUSimLog_CarScanner_NoBrandBluetoothELM327_20230510.txt)

23:20:38.260 -> ------------------- Arduino setup start ---------------------------
23:20:38.260 -> Entering Configuration Mode Successful!
23:20:38.260 -> Setting Baudrate Successful!
23:20:38.260 -> CAN BUS Shield init ok!
23:20:44.026 -> CAN message handle start.
23:20:44.026 -> Msg from canId: 7DF
23:20:44.026 -> PID query: 0
23:20:44.026 -> CAN message handle time (micros): 2656
23:20:44.026 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:20:44.026 -> - SRAM left: 1411
23:20:44.026 -> CAN message handle start.
23:20:44.026 -> Msg from canId: 7DF
23:20:44.026 -> PID query: 0
23:20:44.026 -> CAN message handle time (micros): 8136
23:20:44.026 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:20:44.026 -> - SRAM left: 1411
23:20:44.126 -> CAN message handle start.
23:20:44.126 -> Msg from canId: 7DF
23:20:44.126 -> PID query: 0
23:20:44.126 -> CAN message handle time (micros): 2656
23:20:44.160 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:20:44.160 -> - SRAM left: 1411
23:20:44.160 -> CAN message handle start.
23:20:44.160 -> Msg from canId: 7DF
23:20:44.193 -> PID query: 20
23:20:44.193 -> CAN message handle time (micros): 2740
23:20:44.193 -> Return. Value (with padding): 41,20,FF,FF,FF,FF
23:20:44.193 -> - SRAM left: 1411
23:20:44.226 -> CAN message handle start.
23:20:44.226 -> Msg from canId: 7DF
23:20:44.226 -> PID query: 40
23:20:44.226 -> CAN message handle time (micros): 2740
23:20:44.226 -> Return. Value (with padding): 41,40,FF,FF,FF,FF
23:20:44.226 -> - SRAM left: 1411
23:20:44.260 -> CAN message handle start.
23:20:44.260 -> Msg from canId: 7DF
23:20:44.260 -> PID query: 60
23:20:44.260 -> CAN message handle time (micros): 2740

...

23:20:52.897 -> CAN message handle start.
23:20:52.897 -> Msg from canId: 7DF
23:20:52.897 -> PID query: 0
23:20:52.897 -> CAN message handle time (micros): 2656
23:20:52.929 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:20:52.929 -> - SRAM left: 1411
23:20:52.929 -> CAN message handle start.
23:20:52.929 -> Msg from canId: 7DF
23:20:52.963 -> PID query: C
23:20:52.963 -> CAN message handle time (micros): 2656
23:20:52.963 -> Return. Value (with padding): 41,C,0,0
23:20:52.963 -> - SRAM left: 1411
23:20:52.996 -> CAN message handle start.
23:20:52.996 -> Msg from canId: 7DF
23:20:52.996 -> PID query: D
23:20:52.996 -> CAN message handle time (micros): 2656
23:20:52.996 -> Return. Value (with padding): 41,D,0
23:20:52.996 -> - SRAM left: 1411
23:20:53.196 -> CAN message handle start.
23:20:53.196 -> Msg from canId: 7DF
23:20:53.196 -> PID query: 5
23:20:53.196 -> CAN message handle time (micros): 2656
23:20:53.196 -> Return. Value (with padding): 41,5,0
23:20:53.196 -> - SRAM left: 1411
23:20:53.262 -> CAN message handle start.
23:20:53.262 -> Msg from canId: 7DF
23:20:53.262 -> PID query: C
23:20:53.262 -> CAN message handle time (micros): 2660
23:20:53.262 -> Return. Value (with padding): 41,C,0,0
23:20:53.262 -> - SRAM left: 1411

**Comment by rakshitbharat** [comment]
I changed the device but unfortunately no success.

**Comment by rakshitbharat** [comment]
Is this can bus is correct ?

![IMG_20230513_173652](https://github.com/sugiuraii/ECUSim/assets/17176729/ca07638d-ec2a-4251-a379-6afa0709f93a)

**Comment by sugiuraii** [comment]
![IMG_20230514_111153](https://github.com/sugiuraii/ECUSim/assets/25734871/853d0c73-177f-43ee-b72b-b8ba981d75a5)
![IMG_20230514_111405](https://github.com/sugiuraii/ECUSim/assets/25734871/cd95d0ba-8035-448b-a8a8-c968646ad9b0)

Your can bus board is correct.
I used same kind of board. (Although board model is slightly different, these two board should be equivalent (same MCP2515, same XTAL frequency).

**Comment by rakshitbharat** [comment]
Okay, now I am not getting any idea what is happening and why I am getting 32bit extended ID.

**Comment by sugiuraii** [comment]
Dear,
Thank you for your cooperation.

https://github.com/sugiuraii/ECUSim
https://github.com/sugiuraii/ECUSim/commit/daa47f18aca07fe3d9bf5a527556a672cff98532

I pushed new code on develop branch, to get the content of received message. (Please enable debug switch on ECUSim.h to use this)

I am wondering what kind of message sent on 29bit ID.
If you can ok, could you try it?

**Comment by rakshitbharat** [comment]
Sure,
Let me reach home I will do it soon

**Comment by rakshitbharat** [comment]
please check this log


23:32:51.075 -> ------------------- Arduino setup start ---------------------------
23:32:51.075 -> Entering Configuration Mode Successful!
23:32:51.075 -> Setting Baudrate Successful!
23:32:51.075 -> CAN BUS Shield init ok!
23:34:00.944 -> ------------------- Arduino setup start ---------------------------
23:34:00.944 -> Entering Configuration Mode Successful!
23:34:00.944 -> Setting Baudrate Successful!
23:34:00.944 -> CAN BUS Shield init ok!
23:34:36.338 -> CAN message handle start.
23:34:36.338 -> Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:34:36.338 -> PID query: 0
23:34:36.363 -> CAN message handle time (micros): 6312
23:34:36.363 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:34:36.363 -> - SRAM left: 1415
23:34:36.441 -> CAN message handle start.
23:34:36.441 -> Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:34:36.441 -> PID query: 0
23:34:36.441 -> CAN message handle time (micros): 6312
23:34:36.486 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:34:36.486 -> - SRAM left: 1415
23:34:36.580 -> CAN message handle start.
23:34:36.580 -> Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:34:36.580 -> PID query: 0
23:34:36.580 -> CAN message handle time (micros): 6308
23:34:36.580 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:34:36.580 -> - SRAM left: 1415
23:34:36.797 -> CAN message handle start.
23:34:36.797 -> Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:34:36.843 -> PID query: 0
23:34:36.843 -> CAN message handle time (micros): 7260
23:34:36.843 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:34:36.843 -> - SRAM left: 1415
23:34:36.906 -> CAN message handle start.
23:34:36.906 -> Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:34:36.906 -> PID query: 0
23:34:36.952 -> CAN message handle time (micros): 7256
23:34:36.952 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:34:36.952 -> - SRAM left: 1415
23:34:38.193 -> CAN message handle start.
23:34:38.193 -> Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:34:38.193 -> PID query: 0
23:34:38.193 -> CAN message handle time (micros): 7248
23:34:38.193 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:34:38.193 -> - SRAM left: 1415
23:34:46.555 -> CAN message handle start.
23:34:46.555 -> Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:34:46.555 -> CAM ID do not match with this ECU's ID.
23:34:59.243 -> CAN message handle start.
23:34:59.243 -> Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:34:59.243 -> CAM ID do not match with this ECU's ID.
23:35:05.586 -> CAN message handle start.
23:35:05.586 -> Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:35:05.586 -> CAM ID do not match with this ECU's ID.
23:35:11.934 -> CAN message handle start.
23:35:11.934 -> Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:35:11.934 -> CAM ID do not match with this ECU's ID.
23:35:18.205 -> CAN message handle start.
23:35:18.205 -> Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:35:18.206 -> PID query: 0
23:35:18.206 -> CAN message handle time (micros): 7248
23:35:18.206 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:35:18.206 -> - SRAM left: 1415
23:35:24.597 -> CAN message handle start.
23:35:24.597 -> Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
23:35:24.597 -> CAM ID do not match with this ECU's ID.

**Comment by rakshitbharat** [comment]
http://imsapp.com/ecusim/user_manual_en.pdf
JUST FOR REFERENCE can this user manual from on pf an OBD simulator

![Screenshot_20230515-153127_Adobe Acrobat](https://github.com/sugiuraii/ECUSim/assets/17176729/64d859b4-e7e4-41d8-847c-4582097aff46)

**Comment by sugiuraii** [comment]
Thank you for sending the log.

On you log,

1. At first, your ELM327 try to send the PID (00) request by using 11bit ID.
2. Following your ELM327 request, ECUSim board return the message.
3. Step1-2 repeats by 6 time. (Maybe in this step, the app try to check the ELM327-ECUSim connection)
4. After that, your ELM327 try to send the PID request with using 29bit ID.

On my log,
1. PID 00 query-response repeat by 3 times
2. After that, PID query changes 20->40->60 (Maybe, the app correctly detect  ELM327-ECUSim connection).

---
23:20:38.260 -> ------------------- Arduino setup start ---------------------------
23:20:38.260 -> Entering Configuration Mode Successful!
23:20:38.260 -> Setting Baudrate Successful!
23:20:38.260 -> CAN BUS Shield init ok!
23:20:44.026 -> CAN message handle start.
23:20:44.026 -> Msg from canId: 7DF
23:20:44.026 -> PID query: 0
23:20:44.026 -> CAN message handle time (micros): 2656
23:20:44.026 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:20:44.026 -> - SRAM left: 1411
23:20:44.026 -> CAN message handle start.
23:20:44.026 -> Msg from canId: 7DF
23:20:44.026 -> PID query: 0
23:20:44.026 -> CAN message handle time (micros): 8136
23:20:44.026 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:20:44.026 -> - SRAM left: 1411
23:20:44.126 -> CAN message handle start.
23:20:44.126 -> Msg from canId: 7DF
23:20:44.126 -> PID query: 0
23:20:44.126 -> CAN message handle time (micros): 2656
23:20:44.160 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
23:20:44.160 -> - SRAM left: 1411
23:20:44.160 -> CAN message handle start.
23:20:44.160 -> Msg from canId: 7DF
**23:20:44.193 -> PID query: 20**
23:20:44.193 -> CAN message handle time (micros): 2740
23:20:44.193 -> Return. Value (with padding): 41,20,FF,FF,FF,FF
23:20:44.193 -> - SRAM left: 1411
23:20:44.226 -> CAN message handle start.
23:20:44.226 -> Msg from canId: 7DF
**23:20:44.226 -> PID query: 40**
23:20:44.226 -> CAN message handle time (micros): 2740
23:20:44.226 -> Return. Value (with padding): 41,40,FF,FF,FF,FF
23:20:44.226 -> - SRAM left: 1411
23:20:44.260 -> CAN message handle start.
23:20:44.260 -> Msg from canId: 7DF
**23:20:44.260 -> PID query: 60**
23:20:44.260 -> CAN message handle time (micros): 2740

---

Comparing your log, i am suspecting that the ECUSim response (of PID 00) do not correctly recognized by ELM327.
If this is correct, there might be a trouble in "MCP2515 CAN message transmission" or "ELM327 message detection".

I pushed new commit  to get the return code from MCP2515.
https://github.com/sugiuraii/ECUSim/commit/5ed7b4a560a0bc0e5f06e84ea73e5341feb2a750
On this revision, you can check the return code from MCP2515, on sending/receiving CAN message.
(return 0 should be OK).

01:13:19.977 -> CAN message handle start.
**01:13:19.977 -> MCP read result code: 0**
01:13:19.977 -> Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
01:13:19.977 -> PID query: 0
01:13:20.010 -> CAN message handle time (micros): 8440
01:13:20.010 -> Return. Value (with padding): 41,0,FF,FF,FF,FF
**01:13:20.010 -> MCP send result code :0**
01:13:20.010 -> - SRAM left: 1411
01:13:20.044 -> CAN message handle start.

If you are OK, please try it.

**Comment by rakshitbharat** [comment]
Sure, give me 30minuts will check soon

**Comment by rakshitbharat** [comment]
Meanwhile, can you create any discord server or so, so that we can connect realtime, here the thread became unnecessary long

**Comment by rakshitbharat** [comment]
------------------- Arduino setup start ---------------------------
Entering Configuration Mode Successful!
Setting Baudrate Successful!
CAN BUS Shield init ok!
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8496
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :7
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8524
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :7
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8540
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :7
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8436
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :6
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8436
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :6
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8436
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :6
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
CAM ID do not match with this ECU's ID.
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8440
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :6
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
CAM ID do not match with this ECU's ID.
CAN message handle start.
MCP read result code: 0
Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
CAM ID do not match with this ECU's ID.
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8436
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :6
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
CAM ID do not match with this ECU's ID.
CAN message handle start.
MCP read result code: 0
Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
CAM ID do not match with this ECU's ID.
CAN message handle start.
MCP read result code: 0
Msg from canId: 7DF Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
PID query: 0
CAN message handle time (micros): 8436
Return. Value (with padding): 41,0,FF,FF,FF,FF
MCP send result code :6
- SRAM left: 1410
CAN message handle start.
MCP read result code: 0
Msg from canId: 98DB33F1 Msg length: 8 Msg content: 2,1,0,0,0,0,0,0
CAM ID do not match with this ECU's ID.

**Comment by sugiuraii** [comment]
https://github.com/coryjfowler/MCP_CAN_lib/blob/master/mcp_can_dfs.h

```C
#define CAN_OK             (0)
#define CAN_FAILINIT       (1)
#define CAN_FAILTX         (2)
#define CAN_MSGAVAIL       (3)
#define CAN_NOMSG          (4)
#define CAN_CTRLERROR      (5)
#define CAN_GETTXBFTIMEOUT (6)
#define CAN_SENDMSGTIMEOUT (7)
#define CAN_FAIL       (0xff)
```
Your log invokes errors of 7 and 6.
MCP2515 seems to fail to send the response to ELM327.

**Comment by sugiuraii** [comment]
![238132737-ca07638d-ec2a-4251-a379-6afa0709f93a](https://github.com/sugiuraii/ECUSim/assets/25734871/140b54e1-0bb0-4c1c-8c9f-3dc85a0f50e5)

On your photo, terminator(resistor) jumper of MCP2515 is open.
Have you ever tried with connecting this jumper?

**Comment by sugiuraii** [comment]
![238164293-853d0c73-177f-43ee-b72b-b8ba981d75a5](https://github.com/sugiuraii/ECUSim/assets/25734871/6691beb8-dc12-4837-9b48-5cea2c136b7b)
Like this.

**Comment by rakshitbharat** [comment]
Working with the Jumper 💪
Superb
Lets move this project to next level now.

**Comment by rakshitbharat** [comment]
### Solution 

![Screenshot 2023-05-16 135358](https://github.com/sugiuraii/ECUSim/assets/17176729/ac9f885a-7fc7-4d00-a106-d5c5d7eda29e)

**Comment by sugiuraii** [comment]
I'm glad to hear you solved  the issue.

Following this issue report, I added code to check the error status of MCP2515 send/receive.
And I revised Wiring instruction picture following your comment.
https://github.com/sugiuraii/ECUSim/commit/7e2024c6af0adde52a1d8cd3675be52ea9ae4a93
https://github.com/sugiuraii/ECUSim/commit/5040e476d9522b02d8ff23e805c2efe205e0bfb8

https://github.com/sugiuraii/ECUSim/commits/develop

Thank you for your contribution.
